### ISSUE TITLE
Can't fire a submit event using Nightwatch.js + Testing Library

### ISSUE THREAD

**Issue by lsoares** [testing-library/nightwatch-testing-library#157]
"@testing-library/dom": "^7.26.7",
    "@testing-library/nightwatch": "^2.0.0",
    "@testing-library/user-event": "^12.2.2",
    "chromedriver": "^87.0.0",
    "nightwatch": "^1.5.1"

Node 12.19.0

Relevant code or config

```js
const { getQueriesFrom } = require('@testing-library/nightwatch')
const { fireEvent } = require('@testing-library/dom')

module.exports = {

  async 'Demo test ecosia.org'(browser) {
    await browser.url('https://www.ecosia.org/')

    const { getByPlaceholderText } = getQueriesFrom(browser)

    const searchBox = await getByPlaceholderText(/search the web to plant trees.../i)

    await browser.setValue(searchBox, 'nightwatch')
    await fireEvent.submit(searchBox);

    await browser.end()
  }
}

```

What you did:
`npm t -- tests/ecosiaSearchWithTL.js
`
What happened:

```
[Ecosia Search With TL] Test Suite
==================================
ℹ Connected to localhost on port 9515 (1061ms).
  Using: chrome (87.0.4280.66) on Mac OS X platform.

Running:  Demo test ecosia.org


FAILED: 1 errors (913ms)
   Error: Unable to find the "window" object for the given node. Please file an issue with the code that's causing you to see this error: https://github.com/testing-library/dom-testing-library/issues/new
       at Object.Demo test ecosia.org (/Users/lsr7759/projects/e2e/tests/ecosiaSearchWithTL.js:14:21)
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
_________________________________________________

TEST FAILURE: 1 error during execution; 0 tests failed, 0 passed (2.642s)
```

Repo:
https://github.com/lsoares/e2e-nightwatchjs-testinglibrary

Above, I tried firing an event to submit the form. It failed... but [I also tried using `getByRole` but it also failed for other reason](https://stackoverflow.com/questions/64884748/getbyrole-in-nightwatch-testing-library-throws-error-in-basic-example). I think `getByRole` would be better though.

**Comment by benmonro** [comment]
@lsoares this library was a bit of an experiment I did a while back.  I'm looking for maintainers and happy to hand over the keys if you want to take it over or even just fix this one issue, but I don't have cycles to maintain this anymore.

**Comment by lsoares** [comment]
hey @benmonro 
I'm quite new to Nightwatch.js and TL so I don't think it makes sense to grab it now. If this changes, I'll let you know. Thanks!

**Comment by benmonro** [comment]
Ok no worries let's keep this open just in case someone else is interested
